# Generated by Django 4.2.30 on 2026-04-24 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='coins',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='xp',
            field=models.IntegerField(default=0),
        ),
    ]
