# Generated by Django 4.2.30 on 2026-04-10 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='assistant_percent',
            field=models.IntegerField(default=15),
        ),
        migrations.AddField(
            model_name='group',
            name='teacher_percent',
            field=models.IntegerField(default=40),
        ),
    ]
