# Generated by Django 4.2.30 on 2026-04-10 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_group_assistant_percent_group_teacher_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='lesson_start_time',
            field=models.TimeField(default='10:00'),
        ),
        migrations.AddField(
            model_name='group',
            name='schedule_type',
            field=models.CharField(choices=[('3_days', 'Haftada 3 kun'), ('5_days', 'Haftada 5 kun'), ('daily', 'Har kuni')], default='3_days', max_length=10),
        ),
        migrations.AddField(
            model_name='lesson',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='lesson_type',
            field=models.CharField(choices=[('video', 'Video'), ('pdf', 'PDF'), ('text', 'Matn')], default='text', max_length=10),
        ),
    ]
