# Generated by Django 4.2.30 on 2026-04-11 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_course_teacher_alter_enrollment_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='homework_task',
            field=models.TextField(blank=True, null=True, verbose_name='Uyga vazifa'),
        ),
    ]
