# Generated by Django 4.2.30 on 2026-04-11 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_lesson_homework_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='ended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='homework_image',
            field=models.ImageField(blank=True, null=True, upload_to='lessons/homework/images/'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='homework_video',
            field=models.FileField(blank=True, null=True, upload_to='lessons/homework/videos/'),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
