# Generated by Django 4.2.30 on 2026-04-24 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0002_homework_comment_homework_github_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='coins_awarded',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='homework',
            name='is_bonus_eligible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='homework',
            name='xp_awarded',
            field=models.IntegerField(default=0),
        ),
    ]
